Theming Storybook with an Emulsify theme
emulsify-ds/emulsify-ui-kit pull request #87
Opened 2023-05-25 15:04 UTC by amazingrando

## Theming Storybook with an Emulsify theme

This PR styles the Storybook interface to "brand" it as Emulsify. It is still obviously Storybook, but now it looks like Emulsify's implementation of Storybook.

## How to review this pull request
- [ ] Run `npm run develop`
- [ ] Confirm the interface looks like the image below.
- [ ] Explore the interface—open controls, click on buttons, etc—and confirm there is not something that looks weird or off. (I think I caught all of the edge cases, but I appreciate your eyes on this.)

![CleanShot 2023-05-25 at 10 57 22@2x](https://github.com/emulsify-ds/emulsify-ui-kit/assets/409903/832edbe5-e566-44fe-a3fe-ffe2eba16b9b)

2023-06-21 14:01 UTC, codechefmarc requested changes
Most of this looks good, theming looks as expected. A few spots I noted with screenshots below have color contrast issues, however:
1. I received a notice that Storybook needed an update via a notification bubble:
![Screenshot 2023-06-21 at 6 53 51 AM](https://github.com/emulsify-ds/emulsify-ui-kit/assets/107938318/ebd69d6e-1da0-4888-a7bb-74339f943a8c)
2. Clicking through to where the update notes are (or clicking the three dots in the top next to the Emulsify logo) then clicking about Storybook:
 ![Screenshot 2023-06-21 at 6 53 58 AM](https://github.com/emulsify-ds/emulsify-ui-kit/assets/107938318/f8d3bcf6-3443-441d-97a8-d0db5854d82e)
3. Controls for components have some color contrast for the name of the control, and then the text boxes are red (This was for the Accordion component):
![Screenshot 2023-06-21 at 6 55 08 AM](https://github.com/emulsify-ds/emulsify-ui-kit/assets/107938318/19264917-3480-401f-9837-a1e56d3e6518)
4. Keyboard shortcuts area:
![Screenshot 2023-06-21 at 6 59 41 AM](https://github.com/emulsify-ds/emulsify-ui-kit/assets/107938318/fd5136d4-143e-4b8d-a56b-ac233ce1a691)

2024-02-14 04:31 UTC, mariannuar commented
This ticket is ready for review again. Whoever reviews it, please take it in count that font-sizes values are not being displayed as expected. For example, the cover looks terrible but it's because of that. There's another PR that fixes this. https://github.com/emulsify-ds/emulsify-ui-kit/pull/114

<img width="1276" alt="Screenshot 2024-02-13 at 10 30 55 PM" src="https://github.com/emulsify-ds/emulsify-ui-kit/assets/48533432/eeb9dc06-a547-4b0c-bfe8-0cda690767f6">

2024-02-14 15:43 UTC, amazingrando reviewed
I have a single change to make and this is approved.

2024-02-14 15:43 UTC, amazingrando commented on .storybook/emulsifyTheme.js
> +    'https://randyoest.com/random/emulsify-logo-sb.svg',
I have to replace this image! Yikes!

2024-02-14 15:50 UTC, merged